### ISSUE TITLE
only free software?

### ISSUE THREAD

**Issue by ghost** [avarzille/x15-old#1]
I would want that this microkernel only uses free software, without blobs.

**Comment by avarzille** [comment]
hello,
A few clarifications:

- I'm not the owner of this project, I'm merely a contributor. Richard Braun is the person you want to contact for this kind of matter.
- github issues should be opened for bugs or deficiencies you found in the program. This is more of a philosophical question.
- Given the design of x15, it's unlikely that you'll ever find blobs, given that only a minimum set of drivers will be included. Adding to that, x15 is licensed under the GPLv3+, which doesn't mesh well with binary blobs. I'm not a lawyer, so I may be wrong on that point.

On a more personal level, I agree that a free kernel should be devoid of any blobs. On the plus side, there are fully free kernels :)

Agustina.

**Comment by ghost** [comment]
Good :)
